### ISSUE TITLE
type '[vector_float3]' (aka 'Array<float3>') has no member 'advanced' Error

### ISSUE THREAD

**Issue by arpitjain03** [gao0122/ARKit-Example-by-Apple#9]
Value of type '[vector_float3]' (aka 'Array<float3>') has no member 'advanced'

I am getting above error in Xcode 9 GM seed in Utilities.swift
It was working fine in Xcode beta 3 but it is not working in latest version
Please help me to solve this error.

**Comment by max6363** [comment]
In **Utilities.swift**
you have this,
`let points = features.points`

replace with,
`let points = features.__points`

keep rocking.. Enjoy ... :)

**Comment by arpitjain03** [comment]
Thanks, Its working fine now 👍
